In [12]:
import pandas as pd
import numpy as np

In [13]:
import os

os.getcwd()

'/Users/skyfano/Documents/Masterarbeit/Prediction_of_energy_prices'

In [14]:
df = pd.read_csv('./data/Final_data/final_data_july.csv')
train_df = pd.read_csv('./data/Final_data/train_df.csv')
test_df = pd.read_csv('./data/Final_data/test_df.csv')

In [15]:
df.head()

,Date,Day_ahead_price (€/MWh),Solar_radiation (W/m2),Wind_speed (m/s),Temperature (°C),Biomass (GWh),Hard_coal (GWh),Hydro (GWh),Lignite (GWh),Natural_gas (GWh),...,Lag_1_day,Lag_2_days,Lag_3_days,Lag_4_days,Lag_5_days,Lag_6_days,Lag_7_days,Day_of_week,Month,Rolling_mean_7
0,2012-01-08,26.83,17.54,5.21,3.74,98.605,189.718,48.467,354.178,256.892,...,32.58,36.26,20.35,32.16,35.03,33.82,18.19,6,1,31.00
1,2012-01-09,47.91,13.04,4.24,3.80,98.605,344.154,49.054,382.756,282.438,...,26.83,32.58,36.26,20.35,32.16,35.03,33.82,0,1,33.02
2,2012-01-10,45.77,28.71,4.30,4.81,98.605,360.126,51.143,334.267,267.311,...,47.91,26.83,32.58,36.26,20.35,32.16,35.03,1,1,34.55
3,2012-01-11,47.83,21.58,4.08,5.14,98.605,360.330,50.693,385.000,277.343,...,45.77,47.91,26.83,32.58,36.26,20.35,32.16,2,1,36.79
4,2012-01-12,43.10,25.12,6.77,4.98,98.605,306.521,50.732,332.985,266.820,...,47.83,45.77,47.91,26.83,32.58,36.26,20.35,3,1,40.04

In [16]:
# Assuming df is your DataFrame
df = df.drop(columns=['Lag_1_day', 'Lag_2_days', 'Lag_3_days', 'Lag_4_days', 'Lag_5_days',
                      'Lag_6_days', 'Lag_7_days', 'Rolling_mean_7'])

train_df = train_df.drop(columns=['Lag_1_day', 'Lag_2_days', 'Lag_3_days', 'Lag_4_days', 'Lag_5_days',
                                  'Lag_6_days', 'Lag_7_days', 'Rolling_mean_7'])
test_df = test_df.drop(columns=['Lag_1_day', 'Lag_2_days', 'Lag_3_days', 'Lag_4_days', 'Lag_5_days',
                                'Lag_6_days', 'Lag_7_days', 'Rolling_mean_7'])

In [17]:
# save the dataframe to a new csv file
df.to_csv('./data/Final_data/final_data_no_lags.csv', index=False)
train_df.to_csv('./data/Final_data/train_df_no_lags.csv', index=False)
test_df.to_csv('./data/Final_data/test_df_no_lags.csv', index=False)