# Final Day Ahead Price Prediction

In [1]:
# Import all csv files from the forecasted_data folder and merge them into one csv file
import os
import pandas as pd
from pathlib import Path


def load_and_merge_csv_files(forecasted_data_dir, csv_files):
    # Initialize an empty DataFrame
    merged_df = pd.DataFrame()

    for csv_file in csv_files:
        # Read the CSV file into a DataFrame
        df = pd.read_csv(os.path.join(forecasted_data_dir, csv_file))

        # Merge the DataFrame on the 'Date' column
        if merged_df.empty:
            merged_df = df
        else:
            merged_df = pd.merge(merged_df, df, on='Date', how='outer')

    return merged_df


# Get the current working directory and go one folder up
cwd = Path(os.getcwd()).parent

# Path to the forecasted_data folder after going one directory up
forecasted_data_dir = cwd / 'data' / 'Future_data' / \
    'Manual_simulation' / 'forecasted_data'

# Check if the directory exists
if forecasted_data_dir.exists():
    # Get all the CSV files in the forecasted_data folder
    csv_files = [f for f in os.listdir(
        forecasted_data_dir) if f.endswith('.csv')]
    # Load and merge CSV files
    merged_df = load_and_merge_csv_files(forecasted_data_dir, csv_files)
else:
    print(f"Directory does not exist: {forecasted_data_dir}")

merged_df = load_and_merge_csv_files(forecasted_data_dir, csv_files)

merged_df

,Date,Lignite (GWh),Natural_gas (GWh),Hard_coal (GWh),Biomass (GWh),Other (GWh),Wind_speed (m/s),Temperature (°C),Wind_offshore (GWh),Wind_onshore (GWh),Pumped_storage_generation (GWh),Solar_radiation (W/m2),Net_total_export_import (GWh),Hydro (GWh),Solar_energy (GWh)
0,2024-07-29,236.412769,161.729196,77.131892,114.467181,60.589910,3.763740,19.677840,39.251187,186.406952,20.967216,217.053659,-191.470585,51.164239,274.989011
1,2024-07-30,198.529067,135.785707,72.426480,113.739188,66.760590,3.338270,18.784963,42.308327,194.113928,17.658391,219.402981,1.475163,50.560365,289.499426
2,2024-07-31,208.821403,168.197331,71.723027,114.277482,60.193604,3.523603,20.269650,39.480807,313.203398,20.118478,242.176329,-150.735820,50.425785,260.453237
3,2024-08-01,220.638712,198.698191,106.894001,110.041468,63.041389,3.557334,21.287117,47.330189,357.542795,22.168196,271.883692,-175.684717,50.152274,257.157486
4,2024-08-02,194.058603,134.624710,88.976278,108.614761,58.138594,2.592341,18.286833,66.875940,228.297288,17.953564,194.746012,-160.080532,48.400867,269.136151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,2026-12-27,117.110038,169.146932,45.128759,116.062974,60.615720,4.023179,2.727938,142.636220,524.012611,19.572419,23.109718,-55.377232,46.773712,70.109556
882,2026-12-28,87.176535,180.352931,40.477918,116.144244,55.883586,3.569411,2.533574,162.537815,863.528769,18.342296,22.202108,239.700967,46.392569,44.178287
883,2026-12-29,98.931078,253.753669,53.978579,117.999628,61.870596,5.019709,3.209663,155.986292,1136.581529,25.978222,31.392542,410.843744,49.568048,46.375693
884,2026-12-30,95.350181,223.832415,47.858825,117.413011,60.694992,4.985357,3.785974,165.603991,836.832535,23.985740,31.985752,199.807324,48.644834,70.941593
885,2026-12-31,93.231577,266.481872,40.179891,118.760267,62.707692,5.711891,5.228594,160.682361,981.736809,26.639197,34.201865,241.038869,50.126824,46.725231

In [2]:
csv_files

['Lignite_(GWh)_forecast.csv',
 'Natural_gas_(GWh)_forecast.csv',
 'Hard_coal_(GWh)_forecast.csv',
 'Biomass_(GWh)_forecast.csv',
 'Other_(GWh)_forecast.csv',
 'Wind_speed_(m_s)_forecast.csv',
 'Temperature_(°C)_forecast.csv',
 'Wind_offshore_(GWh)_forecast.csv',
 'Wind_onshore_(GWh)_forecast.csv',
 'Pumped_storage_generation_(GWh)_forecast.csv',
 'Solar_radiation_(W_m2)_forecast.csv',
 'Net_total_export_import_(GWh)_forecast.csv',
 'Hydro_(GWh)_forecast.csv',
 'Solar_energy_(GWh)_forecast.csv']

In [ ]:
# Load the other two files
prices_dir = cwd / 'data' / 'Future_data' / 'Manual_simulation'
'''
gas_prices_dir = os.path.join(
    prices_dir, 'forecast_values_large_730_TTF_gas_price_EUR_MWh_300_32.csv')
gas_prices = pd.read_csv(gas_prices_dir)

oil_prices = pd.read_csv(os.path.join(
    prices_dir, 'forecast_values_large_730_Oil_price_EUR_400_32_large.csv'))
'''

gas_prices_dir = os.path.join(
    prices_dir, 'TTF_gas_price_(€_MWh)_forecast.csv')
gas_prices = pd.read_csv(gas_prices_dir)

oil_prices = pd.read_csv(os.path.join(
    prices_dir, 'Oil_price_(EUR)_forecast.csv'))

In [6]:
gas_prices

           Date  TTF_gas_price (€/MWh)
0    2024-07-29              34.754995
1    2024-07-30              34.545249
2    2024-07-31              35.264297
3    2024-08-01              34.252414
4    2024-08-02              33.585581
..          ...                    ...
881  2026-12-27              40.098785
882  2026-12-28              39.634158
883  2026-12-29              40.861966
884  2026-12-30              38.065668
885  2026-12-31              37.156739

[886 rows x 2 columns]

In [ ]:
# Select only Date and Mean columns
# Create copies before modifying to avoid SettingWithCopyWarning
gas_prices = gas_prices.copy()
oil_prices = oil_prices.copy()

gas_prices = gas_prices[['Date', 'TTF_gas_price (€/MWh)']]
oil_prices = oil_prices[['Date', 'Oil_price (EUR)']]

# Rename mean to gas_price and oil_price
# gas_prices.rename(columns={'Mean': 'TTF_gas_price (EUR/MWh)'}, inplace=True)
# oil_prices.rename(columns={'Mean': 'Oil_price (EUR)'}, inplace=True)

# Set the Date column as the index
gas_prices.set_index('Date', inplace=True)
oil_prices.set_index('Date', inplace=True)

# Merge the gas_prices and oil_prices DataFrames with the merged_df DataFrame
merged_df = pd.merge(merged_df, gas_prices, on='Date', how='outer')
merged_df = pd.merge(merged_df, oil_prices, on='Date', how='outer')

# Drop all rows with NaN values
merged_df.dropna(inplace=True)

# Round all values to 2 decimal places
merged_df = merged_df.round(2)

# Create a column with zeros called "Nuclear_energy (MWh)"
merged_df['Nuclear_energy (GWh)'] = 0

# Rename the "TTF_gas_price (EUR/MWh)" column to "TTF_gas_price (€/MWh)"
merged_df.rename(
    columns={'TTF_gas_price (EUR/MWh)': 'TTF_gas_price (€/MWh)'}, inplace=True)

merged_df

,Date,Lignite (GWh),Natural_gas (GWh),Hard_coal (GWh),Biomass (GWh),Other (GWh),Wind_speed (m/s),Temperature (°C),Wind_offshore (GWh),Wind_onshore (GWh),Pumped_storage_generation (GWh),Solar_radiation (W/m2),Net_total_export_import (GWh),Hydro (GWh),Solar_energy (GWh),TTF_gas_price (€/MWh),Oil_price (EUR),Nuclear_energy (GWh)
0,2024-07-29,236.41,161.73,77.13,114.47,60.59,3.76,19.68,39.25,186.41,20.97,217.05,-191.47,51.16,274.99,34.75,70.67,0
1,2024-07-30,198.53,135.79,72.43,113.74,66.76,3.34,18.78,42.31,194.11,17.66,219.40,1.48,50.56,289.50,34.55,70.03,0
2,2024-07-31,208.82,168.20,71.72,114.28,60.19,3.52,20.27,39.48,313.20,20.12,242.18,-150.74,50.43,260.45,35.26,70.25,0
3,2024-08-01,220.64,198.70,106.89,110.04,63.04,3.56,21.29,47.33,357.54,22.17,271.88,-175.68,50.15,257.16,34.25,66.41,0
4,2024-08-02,194.06,134.62,88.98,108.61,58.14,2.59,18.29,66.88,228.30,17.95,194.75,-160.08,48.40,269.14,33.59,65.15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,2026-12-27,117.11,169.15,45.13,116.06,60.62,4.02,2.73,142.64,524.01,19.57,23.11,-55.38,46.77,70.11,40.10,74.20,0
882,2026-12-28,87.18,180.35,40.48,116.14,55.88,3.57,2.53,162.54,863.53,18.34,22.20,239.70,46.39,44.18,39.63,74.16,0
883,2026-12-29,98.93,253.75,53.98,118.00,61.87,5.02,3.21,155.99,1136.58,25.98,31.39,410.84,49.57,46.38,40.86,75.08,0
884,2026-12-30,95.35,223.83,47.86,117.41,60.69,4.99,3.79,165.60,836.83,23.99,31.99,199.81,48.64,70.94,38.07,74.96,0
885,2026-12-31,93.23,266.48,40.18,118.76,62.71,5.71,5.23,160.68,981.74,26.64,34.20,241.04,50.13,46.73,37.16,75.34,0

### Generate Day of week and month

In [9]:
# Generate a column that contains the day of the week and the month as a number
merged_df['Date'] = pd.to_datetime(merged_df['Date'])
merged_df['Day_of_week'] = merged_df['Date'].dt.weekday
merged_df['Month'] = merged_df['Date'].dt.month
merged_df

,Date,Lignite (GWh),Natural_gas (GWh),Hard_coal (GWh),Biomass (GWh),Other (GWh),Wind_speed (m/s),Temperature (°C),Wind_offshore (GWh),Wind_onshore (GWh),Pumped_storage_generation (GWh),Solar_radiation (W/m2),Net_total_export_import (GWh),Hydro (GWh),Solar_energy (GWh),TTF_gas_price (€/MWh),Oil_price (EUR),Nuclear_energy (GWh),Day_of_week,Month
0,2024-07-29,236.41,161.73,77.13,114.47,60.59,3.76,19.68,39.25,186.41,20.97,217.05,-191.47,51.16,274.99,34.75,70.67,0,0,7
1,2024-07-30,198.53,135.79,72.43,113.74,66.76,3.34,18.78,42.31,194.11,17.66,219.40,1.48,50.56,289.50,34.55,70.03,0,1,7
2,2024-07-31,208.82,168.20,71.72,114.28,60.19,3.52,20.27,39.48,313.20,20.12,242.18,-150.74,50.43,260.45,35.26,70.25,0,2,7
3,2024-08-01,220.64,198.70,106.89,110.04,63.04,3.56,21.29,47.33,357.54,22.17,271.88,-175.68,50.15,257.16,34.25,66.41,0,3,8
4,2024-08-02,194.06,134.62,88.98,108.61,58.14,2.59,18.29,66.88,228.30,17.95,194.75,-160.08,48.40,269.14,33.59,65.15,0,4,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,2026-12-27,117.11,169.15,45.13,116.06,60.62,4.02,2.73,142.64,524.01,19.57,23.11,-55.38,46.77,70.11,40.10,74.20,0,6,12
882,2026-12-28,87.18,180.35,40.48,116.14,55.88,3.57,2.53,162.54,863.53,18.34,22.20,239.70,46.39,44.18,39.63,74.16,0,0,12
883,2026-12-29,98.93,253.75,53.98,118.00,61.87,5.02,3.21,155.99,1136.58,25.98,31.39,410.84,49.57,46.38,40.86,75.08,0,1,12
884,2026-12-30,95.35,223.83,47.86,117.41,60.69,4.99,3.79,165.60,836.83,23.99,31.99,199.81,48.64,70.94,38.07,74.96,0,2,12
885,2026-12-31,93.23,266.48,40.18,118.76,62.71,5.71,5.23,160.68,981.74,26.64,34.20,241.04,50.13,46.73,37.16,75.34,0,3,12

### Load the BEV data

In [10]:
# Import the BEV vehicle data
bev_dir = cwd / 'data' / 'Future_data' / \
    'Manual_simulation' / 'BEV_vehicles_data'
bev_constant = pd.read_csv(os.path.join(
    bev_dir, 'BEV_vehicles_forecast_constant.csv'))
bev_growth = pd.read_csv(os.path.join(
    bev_dir, 'BEV_vehicles_forecast_growth.csv'))
bev_decline = pd.read_csv(os.path.join(
    bev_dir, 'BEV_vehicles_forecast_decline.csv'))

# Convert all Date columns to datetime
bev_constant['Date'] = pd.to_datetime(bev_constant['Date'])
bev_growth['Date'] = pd.to_datetime(bev_growth['Date'])
bev_decline['Date'] = pd.to_datetime(bev_decline['Date'])

### Load old data and combine new and old

In [11]:
df_old = pd.read_csv(
    "/Users/skyfano/Documents/Masterarbeit/Prediction_of_energy_prices/data/Final_data/final_data_no_lags.csv")

# convert Date to datetime
df_old['Date'] = pd.to_datetime(df_old['Date'])
df_old

,Date,Day_ahead_price (€/MWh),Solar_radiation (W/m2),Wind_speed (m/s),Temperature (°C),Biomass (GWh),Hard_coal (GWh),Hydro (GWh),Lignite (GWh),Natural_gas (GWh),...,Solar_energy (GWh),Wind_offshore (GWh),Wind_onshore (GWh),Net_total_export_import (GWh),BEV_vehicles,Oil_price (EUR),TTF_gas_price (€/MWh),Nuclear_energy (GWh),Day_of_week,Month
0,2012-01-08,26.83,17.54,5.21,3.74,98.605,189.718,48.467,354.178,256.892,...,8.039,3.639,251.722,26.066,6,103.71,21.33,286.206,6,1
1,2012-01-09,47.91,13.04,4.24,3.80,98.605,344.154,49.054,382.756,282.438,...,4.942,2.225,153.948,-59.712,6,103.64,22.45,294.593,0,1
2,2012-01-10,45.77,28.71,4.30,4.81,98.605,360.126,51.143,334.267,267.311,...,17.101,2.892,200.075,-31.384,6,104.22,21.95,293.534,1,1
3,2012-01-11,47.83,21.58,4.08,5.14,98.605,360.330,50.693,385.000,277.343,...,10.254,3.059,211.599,-2.110,6,103.93,21.95,295.340,2,1
4,2012-01-12,43.10,25.12,6.77,4.98,98.605,306.521,50.732,332.985,266.820,...,17.576,6.901,477.412,32.997,6,102.26,22.08,294.394,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4581,2024-07-24,66.61,225.04,3.47,17.54,110.007,43.469,85.857,199.246,194.291,...,325.285,49.360,179.921,-168.705,992,75.75,32.63,0.000,2,7
4582,2024-07-25,78.34,272.71,2.12,17.85,110.410,50.676,82.632,195.983,209.610,...,394.116,51.053,42.885,-194.496,992,76.36,31.70,0.000,3,7
4583,2024-07-26,93.04,172.33,2.60,19.09,110.852,42.333,79.531,205.273,205.773,...,256.246,40.449,129.267,-241.786,993,75.21,32.20,0.000,4,7
4584,2024-07-27,80.74,176.67,2.05,19.63,110.479,33.307,74.958,184.012,216.412,...,244.051,2.180,32.001,-251.655,992,74.79,32.90,0.000,5,7
4585,2024-07-28,43.96,235.92,3.48,18.17,110.731,11.629,74.669,141.084,158.503,...,345.645,24.192,171.537,-65.418,992,74.37,33.25,0.000,6,7

In [12]:
df_old["Date"].dtype

dtype('<M8[ns]')

In [13]:
merged_df["Date"].dtype

dtype('<M8[ns]')

In [14]:
bev_constant["Date"].dtype

dtype('<M8[ns]')

In [15]:
# added the BEV data to the merged_df but three times and save each created dataframe as csv
merged_df_constant = merged_df.copy()
merged_df_growth = merged_df.copy()
merged_df_decline = merged_df.copy()

# Merge the BEV vehicle data with the merged_df DataFrame
merged_df_constant = pd.merge(
    merged_df_constant, bev_constant, on='Date', how='outer')
merged_df_growth = pd.merge(
    merged_df_growth, bev_growth, on='Date', how='outer')
merged_df_decline = pd.merge(
    merged_df_decline, bev_decline, on='Date', how='outer')

# Drop all rows with NaN values
merged_df_constant.dropna(inplace=True)
merged_df_growth.dropna(inplace=True)
merged_df_decline.dropna(inplace=True)

# Round all values to 2 decimal places
merged_df_constant = merged_df_constant.round(2)
merged_df_growth = merged_df_growth.round(2)
merged_df_decline = merged_df_decline.round(2)

# Add the merged BEV vehicle data to the df_old DataFrame and then save them each to a CSV file
final_df_constant = pd.concat([df_old, merged_df_constant], ignore_index=True)
final_df_growth = pd.concat([df_old, merged_df_growth], ignore_index=True)
final_df_decline = pd.concat([df_old, merged_df_decline], ignore_index=True)

# Save the merged DataFrames to CSV files
final_df_constant.to_csv('final_df_constant.csv', index=False)
final_df_growth.to_csv('final_df_growth.csv', index=False)
final_df_decline.to_csv('final_df_decline.csv', index=False)